### ISSUE TITLE
build failed, когда при локальном BUILD  SUCCESSFUL

### ISSUE THREAD

**Issue by rinAkhm** [rinAkhm/patterns_aqa2.3#1]
@coursar
1. Прописать в консоле gradlew build 
2. Посмотреть результат локальный результат (BUILD SUCCESSFUL) 
3. Посмотреть сборку через README.md  (статус faild) 

по факту результаты разные 

ожидаемый: результат должен быть одинаковым так и там.  

Не могу понять в чем ошибка, прошу помощи 

![image](https://user-images.githubusercontent.com/59740123/74233564-fcbcc580-4cdb-11ea-8338-5fbef38e806a.png)

![image](https://user-images.githubusercontent.com/59740123/74233603-0e05d200-4cdc-11ea-8173-36d8948dea72.png)

![image](https://user-images.githubusercontent.com/59740123/74233745-4f967d00-4cdc-11ea-9664-1c778b8c5c54.png)

![image](https://user-images.githubusercontent.com/59740123/74234560-21b23800-4cde-11ea-9a4e-8c1e6a4ba949.png)

**Comment by coursar** [comment]
Ваш тест приводит к следующему сценарию:

<img width="579" alt="Снимок экрана 2020-02-11 в 19 49 27" src="https://user-images.githubusercontent.com/3601892/74247324-b2513e00-4d07-11ea-9eef-5c09f807f28d.png">

Окошко выбора даты не закрывается, поэтому вы не можете кликнуть на agreement. Какое разрешение на вашем мониторе?

**Comment by rinAkhm** [comment]
на одном 1366x768 на втором 1920х1080. Широкий экран стоит

**Comment by ArRomanov** [comment]
Переставьте действия по заполнению даты сразу после заполнения города. Просто за открытым календарем тест не может кликнуть по элементу, а поле ввода имени не будет полностью закрыто. Либо нужно кликать по свободному месту на странице, чтобы закрыть календарь

**Comment by rinAkhm** [comment]
спасибо помогло. @coursar , @ArRomanov
